apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::638224466109:role/github_actions_trusted_web_identity_role
      username: github-actions
      groups:
        - system:masters